# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('security_code', models.CharField(max_length=4, verbose_name='\u9a8c\u8bc1\u7801')),
                ('is_active', models.SmallIntegerField(default=0, verbose_name='\u662f\u5426\u901a\u8fc7\u9a8c\u8bc1')),
                ('name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('role', models.CharField(help_text='\u89d2\u8272\u7801', max_length=100, verbose_name='\u89d2\u8272')),
                ('sex', models.SmallIntegerField(choices=[(0, '\u672a\u77e5'), (1, '\u7537'), (2, '\u5973')], verbose_name='\u6027\u522b')),
                ('pass_word', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
                ('remarks', models.CharField(max_length=50, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'simple_user',
                'verbose_name': '\u7528\u6237\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='simpleuser',
            unique_together=set([('phone', 'email')]),
        ),
    ]
