# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2017, 1, 4, 14, 54, 1, 197000, tzinfo=utc))),
                ('create_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'download',
                'verbose_name': '\u4e0b\u8f7d\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u4e0b\u8f7d\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u83dc\u5355ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('type', models.SmallIntegerField(choices=[(0, '\u76ee\u5f55'), (1, '\u83dc\u5355'), (2, '\u529f\u80fd')], db_index=0, verbose_name='\u83dc\u5355\u7c7b\u578b')),
                ('url_code', models.CharField(max_length=100, verbose_name='\u8bf7\u6c42\u8def\u5f84')),
                ('code', models.IntegerField(verbose_name='\u83dc\u5355\u7f16\u7801')),
                ('isvisible', models.CharField(max_length=2, verbose_name='\u662f\u5426\u53ef\u89c1')),
                ('parentid', models.CharField(max_length=10, verbose_name='\u7236\u7ea7\u83dc\u5355id')),
                ('menu_order', models.CharField(max_length=10, verbose_name='\u83dc\u5355\u6392\u5e8f')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u89d2\u8272id')),
                ('role_name', models.CharField(max_length=50, verbose_name='\u89d2\u8272\u540d')),
                ('role_code', models.IntegerField(verbose_name='\u89d2\u8272\u7801')),
                ('create_id', models.IntegerField(verbose_name='\u521b\u5efa\u4ebaid')),
                ('create_name', models.CharField(max_length=50, verbose_name='\u521b\u5efa\u4eba')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272id')),
                ('menu_id', models.IntegerField(verbose_name='\u83dc\u5355id')),
                ('create_id', models.IntegerField(verbose_name='\u521b\u5efa\u4ebaid')),
                ('create_name', models.CharField(max_length=50, verbose_name='\u521b\u5efa\u4eba')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'role_menu',
            },
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7528\u6237id')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('security_code', models.CharField(max_length=4, verbose_name='\u9a8c\u8bc1\u7801')),
                ('is_active', models.SmallIntegerField(default=0, verbose_name='\u662f\u5426\u901a\u8fc7\u9a8c\u8bc1')),
                ('name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('sex', models.SmallIntegerField(choices=[(0, '\u672a\u77e5'), (1, '\u7537'), (2, '\u5973')], default=0, verbose_name='\u6027\u522b')),
                ('pass_word', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
                ('remarks', models.CharField(max_length=50, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'simple_user',
                'verbose_name': '\u7528\u6237\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('last_login_at', models.DateTimeField(default=datetime.datetime(2017, 1, 4, 14, 54, 1, 195000, tzinfo=utc), verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4')),
                ('last_logout_at', models.DateTimeField(default=datetime.datetime(2017, 1, 4, 14, 54, 1, 195000, tzinfo=utc), verbose_name='\u6700\u540e\u9000\u51fa\u65f6\u95f4')),
                ('login_count', models.IntegerField()),
                ('remarks', models.CharField(max_length=50, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'user_login_log',
                'verbose_name': '\u7528\u6237\u767b\u5f55\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u7528\u6237\u767b\u5f55\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237id')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272id')),
                ('create_id', models.IntegerField(verbose_name='\u521b\u5efa\u4eba')),
                ('create_name', models.CharField(max_length=50, verbose_name='\u521b\u5efa\u4eba')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.AlterUniqueTogether(
            name='simpleuser',
            unique_together=set([('phone', 'email')]),
        ),
    ]
