# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161225_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='phone',
            field=models.BigIntegerField(blank=True, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
        migrations.AlterUniqueTogether(
            name='simpleuser',
            unique_together=set([('phone', 'email')]),
        ),
    ]
