# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20161225_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
    ]
