# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20161225_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '\u672a\u77e5'), (1, '\u7537'), (2, '\u5973')], default=0, verbose_name='\u6027\u522b'),
        ),
    ]
