# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField()),
                ('create_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'download',
                'verbose_name': '\u4e0b\u8f7d\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u4e0b\u8f7d\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('sex', models.BooleanField(default=0, verbose_name='\u6027\u522b')),
                ('passwd', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('phone', models.BigIntegerField(verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
                ('remarks', models.CharField(max_length=50, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'simple_user',
                'verbose_name': '\u7528\u6237\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('last_login_at', models.DateTimeField(default=datetime.datetime(2016, 12, 10, 14, 26, 22, 678000, tzinfo=utc), verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4')),
                ('last_logout_at', models.DateTimeField(default=datetime.datetime(2016, 12, 10, 14, 26, 22, 678000, tzinfo=utc), verbose_name='\u6700\u540e\u9000\u51fa\u65f6\u95f4')),
                ('login_count', models.IntegerField()),
                ('remarks', models.CharField(max_length=50, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'user_login_log',
                'verbose_name': '\u7528\u6237\u767b\u5f55\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u7528\u6237\u767b\u5f55\u4fe1\u606f\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='simpleuser',
            unique_together=set([('phone', 'name')]),
        ),
    ]
