# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='sex',
            field=models.IntegerField(default=0, help_text='1\uff0c\u7537\uff1b2\uff0c\u5973', verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='last_login_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 14, 35, 51, 983000, tzinfo=utc), verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='last_logout_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 14, 35, 51, 983000, tzinfo=utc), verbose_name='\u6700\u540e\u9000\u51fa\u65f6\u95f4'),
        ),
    ]
