# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161210_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='phone',
            field=models.BigIntegerField(unique=True, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='last_login_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 13, 33, 38, 652000, tzinfo=utc), verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='last_logout_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 13, 33, 38, 653000, tzinfo=utc), verbose_name='\u6700\u540e\u9000\u51fa\u65f6\u95f4'),
        ),
    ]
